# Generated by Django 5.1.2 on 2024-11-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='categoryname',
        ),
    ]
