# Generated by Django 5.1.2 on 2024-11-07 14:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
