# Generated by Django 5.1.2 on 2024-11-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_product_created_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discounted_price',
            new_name='discount_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_description',
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
