# Generated by Django 5.1.2 on 2024-11-13 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
