# Generated by Django 5.1.2 on 2024-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_delete_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
