# Generated by Django 5.1.2 on 2024-11-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_address',
        ),
    ]
