# Generated by Django 5.1.2 on 2024-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
