# Generated by Django 5.1.2 on 2024-11-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_coupons_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
