# Generated by Django 5.1.2 on 2024-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_shipping_address'),
        ('order', '0009_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='amount',
        ),
        migrations.AddField(
            model_name='orders',
            name='items',
            field=models.ManyToManyField(to='cart.cartitem'),
        ),
    ]
