# Generated by Django 5.1.2 on 2024-12-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_payments_amount_orders_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
