# Generated by Django 5.1.2 on 2024-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_payments_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_status',
            field=models.CharField(choices=[('Payment_Pending', 'Payment Pending'), ('Payment_Succeeded', 'Payment Succeeded'), ('Payment_Failed', 'Payment Failed')], default='Payment_Pending', max_length=50),
        ),
    ]
